<?php
	$this->title = "Zend Mailing Theme";
	$this->headTitle($this->title);
?>

<div class="row">
    <!-- Left area for the mail form and mailing overview -->
    <div class="medium-8 large-6 columns">
        <div class="list">
            <div class="mail-content">
                <?php
                $this->title = 'Nieuw mail bericht opstellen';
                $this->headTitle($this->title);
                echo '<h3>'.$this->title.'</h3>';
                echo '<a href="'.$this->url(array('controller' => 'index', 'action' => 'newmail')).'">New Mail</a>';
                ?>
                <hr>
                <?php
                $this->title = 'Lijst met opgeslagen mails';
                $this->headTitle($this->title);
                echo '<h3>'.$this->title.'</h3>';
                ?>
                <table>
                    <tr>
                        <th>Naam</th><th>Slogan</th><th>Onderwerp</th><th>Thema id</th><th>Datum</th>
                    </tr>
                    <?php foreach($this->allmails as $data) : ?>
                        <tr>
                            <td><?php echo $this->escape($data["name"]); ?></td>
                            <td><?php echo $this->escape($data["slogan"]); ?></td>
                            <td>
                                <a href="/school/zendMailingTheme/public/index/loadwebversion?id=<?php echo $data["id"]; ?>">
                                    <?php echo $this->escape($data["subject"]); ?>
                                </a>
                            </td>
                            <td><?php echo $this->escape($data["theme_id"]); ?></td>
                            <td><?php echo $this->escape($data["date"]); ?></td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </div>
        </div>
    </div>

    
    <!-- Right area for the list -->
    <div class="medium-6 large-6 columns">
        <div class="list">
            <div class="list-content">
                <?php
                $this->title = 'Nieuwe subscriber toevoegen aan de e-maillijst';
                $this->headTitle($this->title);
                echo '<h3>'.$this->title.'</h3>';
                echo '<a href="'.$this->url(array('controller' => 'index', 'action' => 'newsubscriber')).'">New Subscriber</a>';
                ?>
                <hr>
                <?php
                $this->title = 'Lijst met e-mailadressen';
                $this->headTitle($this->title);
                echo '<h3>'.$this->title.'</h3>';
                ?>
                <table>
                    <tr>
                        <th>E-mailaddress</th><th>Authentication code</th><th>Status</th>
                    </tr>
                    <?php foreach($this->email_list as $data) : ?>
                        <tr>
                            <td><?php echo $this->escape($data["email"]); ?></td>
                            <td><?php echo $this->escape($data["auth_code"]); ?></td>
                            <td><?php echo $this->escape($data["status"]); ?></td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            <div>
        </div>
    </div>
</div>

<!--
<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }
</style>
<div id="welcome">
    <h1>Welcome to the <span id="zf-name">Zend Framework!</span></h1>

    <h3>This is your project's main page</h3>

    <div id="more-information">
        <p><img src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" /></p>
        <p>
            Helpful Links: <br />
            <a href="http://framework.zend.com/">Zend Framework Website</a> |
            <a href="http://framework.zend.com/manual/en/">Zend Framework Manual</a>
        </p>
    </div>
</div>
-->