<?php
$this->title = "Zend Mailing Theme";
$this->headTitle($this->title);
echo '<h3>'.$this->title.'</h3>';
?>
<table>
    <tr>
        <th>E-mailaddress</th><th>Authentication code</th><th>Status</th>
    </tr>
    <?php foreach($this->email_list as $data) : ?>
        <tr>
            <td><?php echo $this->escape($data["email"]); ?></td>
            <td><?php echo $this->escape($data["auth_code"]); ?></td>
            <td><?php echo $this->escape($data["status"]); ?></td>
        </tr>
    <?php endforeach; ?>
</table>