<?php
$this->title = 'Lijst met e-mailadressen';
$this->headTitle($this->title);
?>

<table>
	<tr>
		<th>E-mailaddress</th><th>Authentication code</th><th>Status</th>
	</tr>
	<?php foreach($this->list as $data) : ?>
		<tr>
			<td><?php echo $this->escape($data->email); ?></td>
			<td><?php echo $this->escape($data->auth_code); ?></td>
			<td><?php echo $this->escape($data->status); ?></td>
		</tr>
	<?php endforeach; ?>
</table>